spring:
  cloud:
    database: org.springframework.cloud.localconfig.MongoServiceInfoCreator, org.springframework.cloud.localconfig.MysqlServiceInfoCreator
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    mongodb:
      uri: mongodb://CloudFoundry_oa5gu9re_8sdv1031_udd9lqd8:Qdge59mVEoZC2JL1iPryXBMdpcKMMcq2@ds133348.mlab.com:33348/CloudFoundry_oa5gu9re_8sdv1031