---
lucky-word: Harsha Priya
spring
  datasource:
    url: jdbc:mysql://192.168.1.141:3306/world
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect